import { DatabaseApplication } from './supabase';

// Global memory cache for development and fallback
declare global {
  var __asfi_applications__: DatabaseApplication[] | undefined;
}

if (!global.__asfi_applications__) {
  global.__asfi_applications__ = [
    {
      id: 'demo-app-1',
      reference_number: 'ASFI-2026-08149',
      status: 'Pending',
      first_name: 'ABDUL',
      middle_name: 'MALIK',
      last_name: 'MOHAMMAD',
      suffix: '',
      birth_date: '1995-04-12',
      age: 31,
      place_of_birth: 'Davao City',
      gender: 'Male',
      civil_status: 'Married',
      citizenship: 'Filipino',
      religion: 'Islam',
      spouse_name: 'FATIMA MOHAMMAD',
      contact_number: '09171234567',
      email: 'abdul.mohammad@example.com',
      present_address: 'Brgy. 23-C, Isla Verde, Davao City, Davao del Sur',
      occupation: 'Merchant / Self-Employed',
      affiliation_name: 'Davao Muslim Traders Guild',
      affiliation_address: 'Davao City',
      is_underage: false,
      beneficiary_first_name: 'FATIMA',
      beneficiary_middle_name: 'SANTOS',
      beneficiary_last_name: 'MOHAMMAD',
      beneficiary_suffix: '',
      beneficiary_relationship: 'Spouse',
      beneficiary_birth_date: '1997-08-20',
      beneficiary_place_of_birth: 'Davao City',
      beneficiary_address: 'Brgy. 23-C, Isla Verde, Davao City, Davao del Sur',
      beneficiary_contact: '09189876543',
      photo_2x2_url: null,
      photo_2x2_name: 'abdul_photo_2x2.jpg',
      applicant_id_url: null,
      applicant_id_name: 'philsys_national_id.jpg',
      applicant_id_type: 'Philippine National ID (PhilSys)',
      beneficiary_id_url: null,
      beneficiary_id_name: 'fatima_id.jpg',
      consent_data_privacy: true,
      agree_terms: true,
      certify_beneficiary: true,
      confirm_attestation: true,
      printed_name: 'ABDUL MALIK MOHAMMAD',
      date_applied: '2026-09-20',
      created_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'demo-app-2',
      reference_number: 'ASFI-2026-04281',
      status: 'Approved',
      first_name: 'MARIAM',
      middle_name: 'ALI',
      last_name: 'HASSAN',
      suffix: '',
      birth_date: '1988-11-05',
      age: 37,
      place_of_birth: 'Cotabato City',
      gender: 'Female',
      civil_status: 'Married',
      citizenship: 'Filipino',
      religion: 'Islam',
      spouse_name: 'TARIQ HASSAN',
      contact_number: '09205551234',
      email: 'mariam.hassan@example.com',
      present_address: 'Block 4 Lot 8, Buhangin, Davao City',
      occupation: 'Secondary School Teacher',
      affiliation_name: 'Davao City National High School',
      affiliation_address: 'Davao City',
      is_underage: false,
      beneficiary_first_name: 'TARIQ',
      beneficiary_middle_name: 'OMAR',
      beneficiary_last_name: 'HASSAN',
      beneficiary_suffix: '',
      beneficiary_relationship: 'Spouse',
      beneficiary_birth_date: '1985-02-14',
      beneficiary_place_of_birth: 'Cotabato City',
      beneficiary_address: 'Block 4 Lot 8, Buhangin, Davao City',
      beneficiary_contact: '09228889900',
      photo_2x2_url: null,
      photo_2x2_name: 'mariam_photo.png',
      applicant_id_url: null,
      applicant_id_name: 'prc_teacher_license.png',
      applicant_id_type: 'PRC ID',
      consent_data_privacy: true,
      agree_terms: true,
      certify_beneficiary: true,
      confirm_attestation: true,
      printed_name: 'MARIAM ALI HASSAN',
      date_applied: '2026-09-19',
      admin_notes: 'Requirements complete. Verified against PhilSys registry.',
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'demo-app-3',
      reference_number: 'ASFI-2026-01932',
      status: 'Pending',
      first_name: 'IBRAHIM',
      middle_name: 'KHALID',
      last_name: 'SOLAIMAN',
      suffix: 'JR.',
      birth_date: '2009-06-15',
      age: 17,
      place_of_birth: 'Marawi City',
      gender: 'Male',
      civil_status: 'Single',
      citizenship: 'Filipino',
      religion: 'Islam',
      contact_number: '09301112233',
      email: 'ibrahim.jr@student.ph',
      present_address: 'Sitio Muslim, Matina, Davao City',
      occupation: 'Senior High Student',
      affiliation_name: 'Mindanao State University',
      affiliation_address: 'Davao Branch',
      is_underage: true,
      guardian_name: 'KHALID SOLAIMAN SR.',
      guardian_relationship: 'Father',
      guardian_contact: '09193334455',
      beneficiary_first_name: 'KHALID',
      beneficiary_middle_name: 'BEN',
      beneficiary_last_name: 'SOLAIMAN',
      beneficiary_suffix: 'SR.',
      beneficiary_relationship: 'Parent (Mother / Father)',
      beneficiary_birth_date: '1975-01-10',
      beneficiary_place_of_birth: 'Marawi City',
      beneficiary_address: 'Sitio Muslim, Matina, Davao City',
      beneficiary_contact: '09193334455',
      photo_2x2_url: null,
      photo_2x2_name: 'ibrahim_2x2.jpg',
      applicant_id_url: null,
      applicant_id_name: 'msu_student_id.jpg',
      applicant_id_type: 'Student ID (School ID for Minors)',
      guardian_id_url: null,
      guardian_id_name: 'father_drivers_license.jpg',
      consent_data_privacy: true,
      agree_terms: true,
      certify_beneficiary: true,
      confirm_attestation: true,
      printed_name: 'KHALID SOLAIMAN SR. (Guardian of IBRAHIM JR.)',
      date_applied: '2026-09-20',
      created_at: new Date(Date.now() - 7200000).toISOString(),
    },
  ];
}

export const memoryApplications = global.__asfi_applications__;
